### ISSUE TITLE
Scatter plot point selection

### ISSUE THREAD

**Issue by karetsu** [datasciencecampus/zygerria#54] opened 2017-03-24 14:50 UTC
Selecting points on the scatter is more than a little bit broken. 
It appears to think that you are clicking elsewhere on the plot and its very hard to actually select points.

**Comment by nathaneastwood** [comment] 2017-03-24 14:54
Yeah it has always been like that, not entirely sure what the issue is as I am using similar plotly code to that on their webpage.

**Comment by nathaneastwood** [comment] 2017-03-24 16:52
This seems to work ok on Windows, but admittedly it isn't as nice on a Mac...

**Comment by nathaneastwood** [comment] 2017-05-22 15:42
This issue has morphed with the new UI. It seems to work fine for the continuous scale, but for the categorical scale, clicking on a point will select a different point entirely on the app. I suspect that the data are being arranged somewhere within the app and the rows are being selected based on a row index.

**Comment by nathaneastwood** [comment] 2017-05-25 11:15
Since de97fca248606bec71bd5c457be951177a0b94dc, when on the categorical scale the code now highlights the correct point but updates the `selectizeInput` with a different LAD.

However, when on the continuous scale, if you select a point and then change to the categorical scale, it will highlight an incorrect point (the same as what the `selectizeInput` is updated with in the previous example).

**Comment by nathaneastwood** [comment] 2017-05-25 14:44
This is due to the `color = as.formula(paste0("~", colour))` line

**Comment by nathaneastwood** [comment] 2017-05-30 17:17
Fixed as of 8313ee7c30288a0d1e0edc7752b104d2819646dd

**Closed by nathaneastwood** 2017-05-30 17:17 UTC
Labels: bug, scatter plot
